#springdoc.packagesToScan=br.com.kafka.producer.api.web.controller
##springdoc.pathsToMatch=/v1, /api/balance/**
#
#server.port=8090
#
#notifications.topics.producer.topic-notification: topic-notification-message
#notifications.topics.producer.topic-notification-email: topic-notification-email

server:
  port: 8090

notifications:
      topics.producer.topic-notification: topic-notification-message
      topics.producer.topic-notification-email: topic-notification-email

spring:
  kafka:
    consumer:
      enable-auto-commit: false
      auto-offset-reset: latest
      group-id: group-notification
      key-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.deserializer.key.delegate.class: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
#      key.serializer: org.apache.kafka.common.serialization.ByteArraySerializer

